version: '3.9'
services:
  web:
    image: "todoapp:latest"
    ports:
      - "3000:80"
    depends_on:
      - api
  api:
    image: "todoapi:latest"
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017" 
    volumes:
      - "./data:/data/db"
    